#### Preamble ####
# Purpose: I threw a wish (initial scraper) in the well (Hansard website), Don't ask me I'll never tell (because my code is embarrasing), I looked to you as it fell (threw errors), And now you're (Hansard website) in my way (why don't you just have a bulk downloader?), I'd trade my soul for a wish (bulk downloader), Pennies and dimes for a kiss (bulk downloader), I wasn't looking for this (scraping expedition), But now you're in my way (and a conference deadline is imminent).
# The Hansard website has some tres changeable urls for the PDFs so it seems less uncertain to just to get the explicit address of the PDFs instead of using a rule. This scraper gets those URLs. This isn't pretty, but it works.
# Author: Rohan Alexander
# Email: rohan.alexander@anu.edu.au
# Last updated: 31 August 2018
# Prerequisites: You need the pages of the search results.
# To do: 


#### Set up workspace ####
library(tidyverse)
library(rvest)


#### Pages of search results that list the PDFs ####
# Future-Rohan: this doesn't have the 1900 decade, nor 1980 onward. 
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=43;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=44;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=45;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221910s%22;resCount=Default"
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=43;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=44;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=45;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221920s%22;resCount=Default"
# 
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221930s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=43;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221940s%22;resCount=Default"
# 
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=43;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=44;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=45;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=46;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
# "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=47;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default"




#### Load a batch of them ####
pages <- c("http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221950s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221960s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=0;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=1;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=2;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=3;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=4;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=5;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=6;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=7;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=8;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=9;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=10;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=11;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=12;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=13;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=14;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=15;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=16;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=17;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=18;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=19;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=20;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=21;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=22;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=23;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=24;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=25;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=26;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=27;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=28;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=29;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=30;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=31;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=32;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=33;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=34;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=35;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=36;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=37;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=38;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=39;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=40;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=41;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=42;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=43;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=44;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=45;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=46;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default",
           "http://parlinfo.aph.gov.au/parlInfo/search/summary/summary.w3p;adv=yes;orderBy=_fragment_number,doc_date-rev;page=47;query=Dataset%3Ahansardr,hansardr80%20Decade%3A%221970s%22;resCount=Default")

# pages <- pages[1:2] # for testing
# pages <- pages[3:length(pages)]


#### Write a function that rests, then finds the URL of the PDFs on the search result page ####
getter <- function(search_result) {
  Sys.sleep(10)
  read_html(search_result) %>% 
    html_nodes("#results a") %>%
    html_attr('href') %>% 
    as_tibble()
}


#### Map ####
# Initialise an empty list to hold the results
my_data <- list()

# Use the function - it applies the 'getter' function to each element of the pages list and stores the result of each element in an element of the my_data list.
my_data <- map(pages, ~ getter(.x))


# Combine all the results and write to a csv
hansard_pdfs <- bind_rows(my_data)
write_csv(hansard_pdfs, "links19506070s.csv")
