---
title: 'Slide into my mentions, please: Who gets incumbancy advantage in Australia?'
author: "Rohan Alexander"
date: "11/09/2018"
abstract: "I examine Australian hansards to create measures of a politician's importance within parliament. I then show these measures are positively correlated with incumbancy advantage."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction
Understanding the incumbency advantage has been of interest since at least the second election. But biases makes it difficult to estimate. Various approaches have been used to account for this, but they tend to treat incumbents as interchangeable [BE MORE SPECIFIC HERE]. 

In this paper I use Australian hansard records to produce a measure of centrality for each incumbent that I interact with incumbency status in a simple Gelman and King (1990) style model. 

In contrast to Eggers, et al., (2015) who focuses on 1987-2007 and only at a Commonwealth House of Representatives level, I find that [INSERT RESULTS HERE]. 

<!-- Who gets kicked out at an election? Do people at the centre get kicked out? Measure those at the centre by those that have high mentions.  -->

# Data
## Centrality
To construct measures of centrality, or importance, I use the Hansard records for the Australian Commonwealth, and the six states over the period that they are available. For details on the dataset please see Alexander and Alexander. Daily Hansard records were the main level that we considered in that paper, but here were disaggregated them into individual-level records. Sometimes these are just short interjections or notes that are not specific to any particular politician, such as 'Honourable members interjecting'. The high dimensional nature of text data means that the appropriate level and focus of the dataset being analysed tends to be specific to a research question. For instance, in our paper interjections are not important because they do not usually contribute much to defining the topics being discussed. But they are interesting in their own right and @Whyte2017 analysed them in a Canadian context for the period 1926 to 2015 to find that female MPs were more likely to be interrupted than male MPs.

Usually the disaggregation into individual-level records is done by identifying politicians' names in particular patterns. For instance, when Hansard is indicating that a particular person is speaking, as opposed to being mentioned, often the name is in upper case, for instance 'Mr WHITLAM' or 'Mr MENZIES'; followed by a dash or colon; or are next to some title within brackets. There is substantial variation in how the person making a statement is identified. Again some error is introduced at this stage because of inconsistencies over time and between the parliaments. There is considerable variance but on average each daily record had 250 **[UPDATE]** individual-level records, resulting in roughly 15 million rows **[UPDATE]** across the state and federal parliaments.

For more information on this dataset please see Alexander and Alexander and also Appendix X.


## Elections


# Model
Following Gelamn and 

# Results


# Summary and conclusions



